# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e8f00adb68b91e36519f134faaf5c9888177dadfec80469b83f7b2fe1d188d7a640ebc5e025eb9d66cb0158236cc9692085d58cb3b113a307fae304ee23dbb4

test:
  secret_key_base: 80234b5ad05a221bd0fd6f4f67ae204d833548b09ad201892dd3b07b5fc0e526bc9733630342e43e508cf56ac3d9b33a6c8c3fecea3e1b5f3d2e9cce72d9c88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
